### ISSUE TITLE
Level ups giving way more than usual.

### ISSUE THREAD

**Issue by xXFlightPVPXx** [mrtenda/CoilSnake#121]
Hey again.

I just starting testing my hack and whenever I level up Ness, he seems to get a ridiculous amount of stats.

- Offense went up by 120

- Defense went up by 902

- Luck went up by 12039

- Vitality went up by 1928

- Guts when up by 255

- IQ went up by 255.

Is there anyway to change the level up stats? This only happens for Ness.

**Comment by xXFlightPVPXx** [comment]
Whoops, Never mind. It's in stats_growth_vars.yml. Sorry!

**Comment by LittleCube13** [comment]
Here, why don't you go [here](https://forum.starmen.net/forum/Community/PKHack) you can sign up for an account, and post in the TroubleShooting topic if you need any more help.

I'm only telling you this so that the CoilSnake repo can slow down a bit on issues that don't pertain to code/CoilSnake not doing its job correctly. :)
