### ISSUE TITLE
Animation Module

### ISSUE THREAD

**Issue by john-soklaski** [mrtenda/CoilSnake#156]
Hey, I'm interested in implementing the animation module. Based on http://datacrystal.romhacking.net/wiki/EarthBound:ROM_map, this includes:

Animation Data: Carpainter's Lightning - Reflected
Animation Data: Carpainter's Lightning - Strike
Animation Data: Starman Junior's Teleport
Animation Data: "BOOM!"
Animation Data: Zombie Attack
Animation Data: "The End?"

I see the pointer table that references these is already in eb.yml as ANIMATION_SEQUENCE_POINTERS.
Do you know how these images are encoded? And is there any existing work / knowledge about this that you're aware of?

**Comment by ShadowOne333** [comment]
Hi John.
First of all, let me thank you for the amazing work you are doing into this project.

Now to answer your question.
I do not have the info on most of the animations.
However, I do have "The End?" animation documented in the translation tutorial of CoilSnake found here:
https://github.com/mrtenda/CoilSnake/wiki/Tutorial%3A-Translating-%22THE-END...-%3F%22-text

I did the entire entry, so if you have questions for that particular animation, let me know.
Apparently that one is 2bpp, but I'm not sure about the rest.
You can try doing a decompression of each Animation data bank with exhal, then try to open them in Tile Molester or some other tile editor, that might help you know exactly how the images are encoded.

**Comment by mrtenda** [comment]
I also don't know much about these images, but I can speculate on how they work based on my knowledge of other things in EB and from looking at Shadow's documentation on the "The End?" graphic.

Graphics like these in EarthBound generally have 3 components: the graphic data, the palette data, and the arrangement data. The graphic data defines each square graphic "tile" of the graphic (which are the little square tiles you see in Tile Molester). The palette determines what color each tile pixel value represents. The arrangement is basically a matrix of tile IDs that tells the game how to arrange the tiles to form the full image. For graphics with arrangements, such as those here, they are generally done by using multiple arrangements which the game animates between.

From looking at Shadow's documentation, it looks like for "The End?" graphic, the arrangement and tiles are both stored inside the same compressed block whose address is listed in the ROM map. I suspect that the palette is probably in there as well. Most of the time in EB, the tiles are the only thing compressed in the block and the arrangement and palette are stored uncompressed in another part of the ROM, but sometimes everything is compressed in a single block like this. In the code, you will first want to decompress the entire block from the rom, and then read the animation/palette/tiles from the decompressed block itself.

My suggestion would be to start with the "The End?" graphics/animation, since Shadow has documented that pretty well already. My guess is that the others work similarly to it.

Hope that information helps in some way, let me know if there's any other information I can provide.

**Comment by john-soklaski** [comment]
Thanks so much for both of your help! 

The tutorial was great in getting started, I hadn't thought to use exhal like that. It made it much easier to explore and figure out the correct format for the tiles.

Thanks especially for the hint that the palette and arrangements were actually contained with the compressed data, rather than separately.

Based on all of this, I was able to get decompilation working. It extracts the six animations, with each frame being a separate png file: https://github.com/mrtenda/CoilSnake/compare/master...john-soklaski:animation_module

Actually, it turns out what the ROM Map had specified as "Animation Data: Carpainter's Lightning - Reflected" is the Camera shutter animation. :)

**Comment by mrtenda** [comment]
Excellent, glad to hear that you got it working!! I looked over your code too and it all looks solid.

By the way, how did you determine that the arrangements were 32x28 tiles? I ask just because the past I had made the assumption based on the SNES's resolution that it was 32x28 tiles for all full-screen, but then later I found out that some arrangements (such as the gas station graphics) are actually stored in the game as 32x32 and I was ignoring the last 4 rows, which resulted in some weird bugs.

**Comment by john-soklaski** [comment]
I was able to figure out the dimensions of the arrangements, because they are stored along with the graphics and palette in the compressed block. Since I know the size of the decompressed block, once I was able to figure out what was graphics and palettes, the remaining size of the block was arrangements.

So, for "The End", I found the arrangements started at 0x128 and the whole block ended at 0xF28. This leaves us with 0xE00 bytes of arrangements. I divide this by two because each tile in an arrangement takes two bytes: 1792 tiles. Then, there are two frames of animation, 896 tiles per frame, which is 32 * 28.

**Comment by mrtenda** [comment]
Oh, perfect, sounds good. I just remember I had made a mistake with this before, but it looks like you avoided it already.

**Comment by john-soklaski** [comment]
I appreciate it :) It's so easy to get the details of this stuff wrong

**Comment by ShadowOne333** [comment]
Amazing work!
Glad you got this sorted out :)

**Comment by john-soklaski** [comment]
I've gotten the animations successfully written back into the Rom and they look to be playing correctly:
https://github.com/john-soklaski/CoilSnake/commit/3544b8410e044537a9ce64aa21f0302373810b2f

The main snag was ensuring that the `is_priority` bit on the tilesets were set for the animations. Otherwise, the animation would play but appear behind the level.

I have a few questions:
1. It looks to be that the `num_tiles` parameter could be removed from the constructor of `EbGraphicTileset`, and subsequently the `num_tiles_maximum` member. Due to this parameter, I currently need to calculate the total number of possible tiles that could occur in an animation before I create the `EbGraphicTileset`, but it seems unnecessary to me. Is there a usage that I am missing?

2. I would like to relocate the animation table in order to support more than the built in six animations. I imagine this would be similar to how the swirl module relocates its table using a patch. Where is a good place to start here?

**Comment by mrtenda** [comment]
Sorry for the delayed response, I lost power for a while due to the hurricane. But good job, that's awesome that you got the animations working!!

In reply to your questions:
1. I don't think this parameter can be removed so easily. When a graphic tileset is read by EarthBound's programming, it expects that graphic tileset to contain a certain number of tiles. If this assumption doesn't hold, EB's programming may act in unexpected ways.
2. The ASM hacking involved here was done by someone else rather than me, so I wouldn't know how to do this kind of change myself. But I think the basic process is to use a SNES debugger to find where in the game's programming it is getting the address for the table, and then going in and modifying that ASM. I can ask around on the slack channel and see if anyone would know how to do this.

**Comment by john-soklaski** [comment]
Sorry for taking so long to get back to this. I took some time and learned 65816 assembly and worked on disassembling the routines involved with animations.

I've added support for relocating the animation table as well as adding more than six animations:
https://github.com/john-soklaski/CoilSnake/compare/3544b8410e044537a9ce64aa21f0302373810b2f...animation_module


Also, I looked into how the playback of animations are controlled. Animations are instantiated using the same command that regular sprites are instantiated:
`[1F 15 {short sprite} {short move} {byte style}]`

For instance, this is the command to instantiate starman's teleport animation:
`[1F 15 2F 01 6E 02 01]`

`[1F 15]` is the opcode for instantiating sprites
`0x012F` is the index of the starman sprite that appears at the end of the animation.
`0x026E` is the index into the movement code pointer table.
`0x01` is the code for "Instant Appearance" (See [Effects](https://datacrystal.romhacking.net/wiki/EarthBound:Standard_Arguments#Effects))



The animations themselves are controlled via movement control codes. I've recreated starman's teleport animation using commands from ebpp:
```
import ebpp

ROM[0xC31000] = {
    mov_jsrmov(0x3C1D)
    mov_rtl
}

new_starman: {
    mov_jslasm(0xC0A864) "[01]"
    mov_movy(0xFFF0) // Move the active sprite's y position in pixels (appears after animation is finished)
    "[25 F0 9F]"
    "[39]"
    "[3B FF]"

    mov_loop_start(4)
    
    mov_tablewrite(0, 0x000d)
    mov_jslasm(0xC474A8) // Flash screen white (Add intensity set in table slot 0 to all color channels for the whole screen) 
    mov_pause(7)
    
    mov_tablewrite(0, 0x0000)
    mov_jslasm(0xC474A8) // Return screen to normal 
    mov_pause(7)

    mov_loop_end

    mov_tablewrite(0, 3) // Play animation 3
    mov_tablewrite(1, 0) // Start animation on frame 0
    mov_tablewrite(2, 6) // Play a duration of 6 frames
    mov_tablewrite(3, 8) // Not sure. 8 Frames total? This controls the speed of the animation
    mov_jslasm(0xC47A9E) // Setup the animation

    mov_jslmov(0xC31000) // Let the animation play for the 6 frames
    // (Was mov_jsrmov(0x3C1D), but this gets put in a different bank, so we need jsl)

    mov_jslasm(0xC0AA6E) "[04 00]" // No idea
    "[3B 00]"
    mov_jslasm(0xC0A4BF)

    mov_tablewrite(1, 6) // Start animation on frame 6
    mov_tablewrite(2, 2) // Play a duration of 2 frames

    mov_jslmov(0xC31000) // Let the animation finish playing

    mov_jslasm(0xC4981F)
    mov_jslasm(0xC4800B)
    mov_jslasm(0xC46E46)

    mov_halt
}

mov_link(0x00d1, new_starman)
```

There are still some loose ends to tie up. Some of the code needs to get cleaned up still and there are still some parameters that I'm unsure of. I also intend to create a few ccscript commands to make it easier to play the animations.

**Comment by mrtenda** [comment]
Awesome, this is amazing! I briefly looked over the code and it all looks good to me. You learned this stuff fast.

**Comment by mrtenda** [comment]
Merged in with https://github.com/mrtenda/CoilSnake/commit/50d0fa9525746c63fad2c782fa32785528f6d97e !
