### ISSUE TITLE
Can't decompile script

### ISSUE THREAD

**Issue by K-irk** [mrtenda/CoilSnake#170]
Every time I try to decompile the script to edit text, it won't decompile. The green bar constantly moves around, but no progress is made.

**Comment by mrtenda** [comment]
Does anything show up in the logs? You can enable more detailed logging by clicking "Enable Debug Mode" in the menu.

**Comment by K-irk** [comment]
I'm not finding any logs actually. Sorry it took me a while to realize you responded.

**Comment by redmagejoe** [comment]
Bumping this, having the exact same issue and it is MADDENING, as I am attempting to merge/diff/cherrypick MaternalBound Rated M and MaternalBound Literal Rated M. There were some choices to not revert from NOA localization made in MaternalBound that I don't quite agree with (such as "evil messages rather than good" not being reverted to "messages from the Devil rather than from God"), and I wanted to make my own fork patch. Here is the error I get when attempting to decompile any scripts from any version of the game:

`Error
Traceback (most recent call last):
  File "D:\Users\Super\Onedrive\Dokumentai\GitHub\CoilSnake2\coilsnake\ui\common.py", line 238, in decompile_script
  File "C:\Users\Super\AppData\Local\Programs\Python\Python36\lib\site-packages\CCScriptWriter\CCScriptWriter.py", line 206, in loadDialogue
  File "C:\Users\Super\AppData\Local\Programs\Python\Python36\lib\site-packages\CCScriptWriter\CCScriptWriter.py", line 474, in getText
  File "C:\Users\Super\AppData\Local\Programs\Python\Python36\lib\site-packages\CCScriptWriter\CCScriptWriter.py", line 595, in getLength
KeyError: 110`

I dug around for old versions of CoilSnake, like 3.01, and all give the exact same error. I have searched for hours on end for an alternative tool or solution to this, and I'm at wits end. I've even seen someone mentioning the problem on Starmen forums as being "an issue with CCScriptWriter, not CoilSnake", but that response really doesn't help given that CCSW is baked into CoilSnake.

**Comment by mrtenda** [comment]
Are you trying to decompile a MaternalBound ROM? I don't think that'll work with the current version of CoilSnake. Perhaps @ShadowOne333 could help you, since he created MaternalBound

**Comment by ShadowOne333** [comment]
Sadly, decompiling an already patched ROM's script is not feasible.
Mostly because some hacks rely heavily on ASM patches done through ccscript files (.ccs), so CoilSnake doesn't know what to do in these instances, since ASM hacks can affect anything in the ROM.

It can only go as far as to decompile some text if it's located in the same place as original EB, but you won't get much out of trying to decompile any CoilSnake-compiled ROM.

With that said, why didn't you just download the source files for the Optional Patches?
It's in the very OP of the MaternalBound thread:
https://forum.starmen.net/forum/Community/PKHack/WIP-MaternalBound-Uncensoring-Other-junk-hack/page/1#post2047150

Specifically here:

> Optional Patches:
> 
> These includes 6 patches:
> 
>     MaternalBound Omega – Rated M & MaternalBound Omega – Rated M + Run
>     These pair of patches are the main MaternalBound hack with some of the offensive lines restored. (They’re not that many offensive lines though, less than 5).
>     Mother 2 1:1 Literal & Mother 2 1:1 Literal + Run
>     These patches include a literal 1:1 translation to keep it as close as possible with the original release of Mother 2.
>     These includes the Octopus/Kokeshi statues as well as the original spanking sound, and other japanese-only jokes.
>     Mother 2 1:1 Literal Rated M & Mother 2 1:1 Literal Rated M + Run
>     Same as the last one, except this one restores some of the offensive lines omitted from the NOA localization.
> 
> Get the optional patches over here!
> https://forum.starmen.net/forum/Community/PKHack/WIP-MaternalBound-Uncensoring-Other-junk-hack/page/17#post2152550
> And their source files for CoilSnake from here!

http://www.bwass.org/bucket/MaternalBound_Optional_Patches_(Source_Files).rar
