### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by Zeklund** [mrtenda/CoilSnake#171]
Hi! I’m kinda new to all this and trying to translate EarthBound into Finnish. When I’m compiling this project it’s all good but after including in it my modified item_configuration_table it immediately says this.

Starting compilation…
- Traceback (most recent call last):
File “coilsnake\ui\gui.pyo”, line 253, in _do_compile_help
File “coilsnake\ui\common.pyo”, line 91, in compile_project
File “coilsnake\util\common\project.pyo”, line 51, in load
AttributeError: ‘unicode’ object has no attribute ‘name’

ERROR: ‘unicode’ object has no attribute ‘name’

What could be the cause?

**Comment by Zeklund** [comment]
I also have a problem separately with my enemy_configuration_table file. It gives me this error:

TableError: TableError: Error while parsing in "Name":
unsigned byte integer is greater than maximum

ERROR: TableError: Error while parsing in "Name":
unsigned byte integer is greater than maximum

**Comment by Timur13240** [comment]
'unicode' error:
This problem maybe caused by the presence of 'unicode' characters in the path of your project or the path to your ROM.
For example:

> C:\Users\Тимур\Desktop\ROMHACKING\ROM\Earthbound (U).smc

Where the word "Тимур" is the name of the computer, and this combination of letters is also the symbol of Russian letters unicode. Check if there are any unicode characters in your path.
