### ISSUE TITLE
Problems with "keyboard"

### ISSUE THREAD

**Issue by Timur13240** [mrtenda/CoilSnake#172]
In the language into which I want to translate EarthBound, more letters than in English. And because of this, I ran into a problem
![keyboard_problem](https://user-images.githubusercontent.com/46261539/51605172-7ac6f680-1f38-11e9-86f4-8cfc324a4499.png)
Not all letters from my alphabet fit into the "keyboard for entering characters names".
How can this problem be solved?

**Comment by ShadowOne333** [comment]
Seems like you already found how to edit the "small" and "CAPITAL" words.
As for the letters themselves, you need to modify the letter table for the Naming Screen.

If you would, please take a look at the following .ccs files that I used for the Spanish translation (both of which were originally made by TragicManner):

Translate words in the Naming Screen:
https://github.com/ShadowOne333/EarthBound-Spanish-Translation/blob/master/ccscript/asm_naming_screen.ccs

Letter table for the Naming Screen:
https://github.com/ShadowOne333/EarthBound-Spanish-Translation/blob/master/ccscript/asm_naming_screen_characters.ccs

Now for the second one (which is the one you should focus on) you will notice a pattern like "[71 2F 72 2F...]"
Every 2F is the separation between each character, you should leave those alone.
Same for the 18 05 XX YY ones that appear, those are the ones that separate the letters from the symbols and the rows. For example, 18 05 16 00 starts printing the next letter/symbol at tile #16 in a horizontal row, while something like 18 05 00 01 starts printing the next letter/symbol in the next row (below).

The ones that matter are the 71, 72, etc.
Those are the upper case alphabet letters from the original EarthBound.
71 = A, 72 = B, etc.
Those are the ones you should change accordingly.
For example, if you don't want the odd symbols in your naming screen, you can always change, let's say, [2F 5D 2F 53] for something like [2F A0 2F A1]. Doing that will make whatever characters you have added in the Fonts 0.png in place of the dash (-) and the centered dot.

If you have any doubts about implementing it, let me know, I'll gladly walk you through it.
I might even add a new entry in the Tutorial section just for this, since I am just realizing there is no entry for changing the Naming screen characters at all.
