### ISSUE TITLE
Decompiling/Compiling hacks together

### ISSUE THREAD

**Issue by JulesTheDemon** [mrtenda/CoilSnake#183]
Okay, so. I'm trying to combine a few romhacks' attributes together. My goal is to combine the "Earthbound Deluxe" hack with (some of) the sprites from Earthbound Enhanced, add a run button, and if possible keep the original Earthbound Enemy Names.

Whenever I decompile EBEnhanced or EBDeluxe I get an error like this after it stops at Swirls:

`ERROR: list index out of range`

Whenever I try and compile it gives me this:

`ERROR: 'Project' object has no attribute 'version'`

I have NO idea what to do. Please help. :(

**Comment by LittlestCube** [comment]
It is shockingly hard to find a modified EarthBound ROM that decompiles well with CoilSnake. Usually you'll only get to the Swirls and you'll get an error like that and that'll be the end of it.

The reason it won't compile: because CoilSnake didn't finish the _decompilation_, there is no Project.snake file, which is ultimately necessary for any CoilSnake project to compile at all. Thus the `ERROR: 'Project' object has no attribute 'version'` error. The Project.snake file is the `'Project' object` the error is referring to.

**Comment by JulesTheDemon** [comment]
I'm a bit confused on what you mean with the last side note. This is what I gathered, at least for what my goal is:

-Decompile a clean Earthbound ROM
-Enable the running patch
-Replace the Battle Sprites with the ones from Earthbound Enhanced
-Compile the ROM
-Patch ROM with Earthbound Deluxe

Is this... accurate, or?

**Comment by LittlestCube** [comment]
If, when you decompiled the EarthBound Enhanced ROM, CoilSnake successfully got to the BattleSprites folder (unsure as to whether this is before or after the Swirls) you should just be able to copy/paste that BattleSprites folder into the clean project, even if the decompilation wasn't complete. Then compile the clean project, and CoilSnake should add the Enhanced sprites in.

**Comment by ShadowOne333** [comment]
CoilSnake doesn't handle decompiling already compiled hacks due to two big reasons:
ASM Hacks & Pointers

You see, usually ASM hacks are included in script files (.ccs). It's an easy way to make assembly hacks without needing an actual 65816 compiler, like xkas for example.
ASM hacks modify a lot of stuff in the game, and also, don't forget that once a project is compiled with CoilSnake, most likely all assets used/required by CoilSnake are shifted around in the ROM, so when CoilSnake tries to decompile an already hacked ROM, it will fail due to that.

The best bet you have is to get yourself the EB Enhanced source files, drag the BattleSprites folder, and by some miracle find the EB Deluxe hack source files. 
Without the source files of EB Deluxe, there's not much you can do outside of maybe over-patching an IPS of a ROM with the new sprites compiled, but then again, you risk the data being shifted around, and possibly overwriting stuff from EB Deluxe.

**Comment by goyangistudios32** [comment]
Mine just opened a text box
